#   //-----------=========-----------\\
#  ||    Welcome to MCWiki's config   ||
#   \\-----------=========-----------//

#Some quick doublechecks:
#Use spaces instead of tabs

#This determines the source language (if using default minecraft wiki).
#Defaults to en for English: minecraft-en.gamepedia.com
#examples: de for Deutsch, es for Espanol, etc. 

language: en

#Using book instead of chat to display info.
#Defaults to true

bookmode: true

#How many <p> elements to show in the chat before stopping.
#Defaults to 5. Only effects if bookmode is false.

cutoff: 5

#The source domain to pull wiki pages from. 
#Can be set to any wiki-like formatted site. 
#Defaults to minecraft.gamepedia.com

customsite: minecraft.gamepedia.com

#This section configures the formatting for each element encountered in the wiki page.
#These are valid HTML elements such as <i> for italic, <a> for link, etc
#the JSON values for each are entirely configurable, including hover and click action and values.
#The prefix and suffix strings mark the beginning and end of elements.

format:
  b:
    bold: true
    color: dark_aqua
  a:
    prefix: '['
    suffix: ']'
    color: aqua
  i:
    italic: true
  h1: 
    underlined: true
    color: dark_grey
   
 #(note that the link <a> overrides hover text and click action based on link content.)
