#   //-----------=========-----------\\
#  ||  Welcome to McWiki's config.    ||
#   \\-----------=========-----------//

#Some quick doublechecks:
#Use spaces instead of tabs
#make sure youre indenting properly!

#This determines the SOURCE LANGUAGE to obtain articles from.
#Defaults to en for English: minecraft-en.gamepedia.com
#examples: de for Deutsch, es for Espanol, etc. 

language: en

#Whether to use the chat, or the default method of a book.
#Defaults to true

bookmode: true

#How many <p> elements to show in the chat before stopping.
#Defaults to 5. Only effects if chatmode is true.

chatcutoff: 5

