name: Wiki
main: io.github.skyylord.McWiki.Wiki
version: 2.0


commands: 
  wiki:
    description: main command.
    permission: mcwiki.wiki
permissions:
  mcwiki.*:
    description: all commands
    default: true
    children:
      mcwiki.wiki: true
  mcwiki.wiki:
    description: perm node for wiki
    default: true