name: McWiki
main: io.github.skylerdev.McWiki.McWiki
version: 2.0
description: A robust and complete minecraft wiki integration into the game.
author: EdgyKid


commands: 
  wiki:
    usage: /<commmand> <article>
    description: Gives the sender the minecraft wiki article for article.
    permission: mcwiki.wiki
  mcwiki: 
    usage: /<command>
    description: Meta information about mcwiki.
    permission: mcwiki.mod
  
permissions:
  mcwiki.wiki:
    description: Permission for /wiki
    default: true
  mcwiki.mod:
    description: Permission for /mcwiki
    default: op