name: McWiki
main: io.github.skylerdev.McWiki.McWiki
version: 2.1
description: A robust and complete minecraft wiki integration into the game.
author: EdgyKid


commands: 
  wiki:
    usage: /wiki <article>
    description: Gives the sender the minecraft wiki article for article.
    permission: mcwiki.wiki
  mcwiki: 
    usage: /mcwiki
    description: Meta information and help.
    permission: mcwiki.mod
  
  
permissions:
  mcwiki.wiki:
    description: Permission for /wiki
    default: true
  mcwiki.mod:
    description: Permission for /mcwiki
    default: op